# Created by Ava St. John and Ingrid Avendano on 9/23/13.
#
#
# Project Euler - Problem 2:
#
# Each new term in the Fibonacci sequence is generated by adding 
# the previous two terms. By starting with 1 and 2, the first 10 
# terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.

def fib(num):
	total = 0
	first_fib_num = 1
	second_fib_num = 2

	while second_fib_num <= num:

	    # only stores even valued numbers to total
	    if second_fib_num % 2 == 0:
	        total += second_fib_num

	    second_fib_num += first_fib_num
	    first_fib_num = second_fib_num - first_fib_num
	
	return total 


def main():
	total = fib(4000000)
	print "Solution to problem 2:", total


main()