# Created by Ingrid Avendano on 11/4/13. 
#
#
# Project Euler - Problem 45: Triangular, pentagonal, and hexagonal
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following 
# formulae:
#
# Triangle    Tn = n*(n+1)/2      1, 3, 6, 10, 15, ...
# Pentagonal  Pn = n*(3*n - 1)/2  1, 5, 12, 22, 35, ...
# Hexagonal   Hn = n*(2*n - 1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.


def triangle(n):
	t = (n*(n + 1))/2.
	return t


def pentagonal(n):
	p = (n*(3*n - 1))/2.
	return p


def hexagonal(n):
	h = n*(2*n - 1)
	return h


def main():
	# range was set by guessing a high limit
	numbers = range(0,56000)
	tri_numbers = []
	hex_numbers = []
	solution = 0

	# triangle numbers
	for n in numbers:
		tri_num = (n*(n + 1))/2.
		tri_numbers.append(tri_num)

	# pentagonal numbers
	for n in numbers:
		pent_num = (n*(3*n - 1))/2.
		if pent_num in tri_numbers:
			hex_numbers.append(pent_num)

	# hexagonal numbers
	for n in numbers:
		hex_num =  n*(2*n - 1)
		if hex_num in hex_numbers:
			solution = hex_num

	print "Solution to problem 45:", solution
	

main()
